### PR TITLE
Bump is-primitive

### PR DESCRIPTION
**Pull request by roderickhsiao**
@jonschlinkert I guess there is no breaking changes in this PR for is-primitive
https://github.com/jonschlinkert/is-primitive/pull/2

### CODE REVIEW

**Comment by jonschlinkert** [comment]
you're right, no breaking changes, and the newer version is more performant. thanks for the pr.

**Comment by roderickhsiao** [comment]
thanks :), would be good to have a npm release for the dependency upgrade

**Comment by jonschlinkert** [comment]
bumped and published. thanks again!

**Comment by jonschlinkert** [comment]
and tagged... https://github.com/jonschlinkert/is-equal-shallow/releases/tag/0.1.3

**Comment by roderickhsiao** [comment]
Bravo!

**Pull request merged**
